### ISSUE TITLE
Where to put async locale set

### ISSUE THREAD

**Issue by rivella50** [jama5262/jiffy#153]
Hi there,
where do i have to put
`await Jiffy.locale('de');`
in order that the locale is set app wide?
When inserting in my async main method i get this error: Unsupported operation: Cannot modify unmodifiable map
This could be since i init MaterialApp (with localizationsDelegates and supportedLocales) after this call, but this is not async anymore there.

**Comment by hao-li** [comment]
change pubspec.yaml:
```yaml
dependencies:
  jiffy:
    git:
      url: https://github.com/hao-li/jiffy.git
      ref: develop
```

`Format Dates` and `Relative Time` will support locale  by parameter.
```dart
Jiffy('20191016', null, 'de').format('yMMMd') => 'Mi., 16. Okt. 2019'
```
No need `await Jiffy.locale('de');`.
